package pt.iscte.es2.optimization_job_runner.post_processing;

import pt.iscte.es2.optimization_job_runner.jmetal.solution.SolutionQuality;

import java.io.Serializable;

/**
 * Value oject representing a solution generated by jmetal
 */
public class AlgorithmSolutionQuality implements Serializable {
	private final String algorithmName;
	private final String solution;
	private final SolutionQuality solutionQuality;

	/**
	 * Constructor
	 * @param algorithmName algorithm name
	 * @param solution solution
	 * @param solutionQuality solution quality
	 */
	public AlgorithmSolutionQuality(String algorithmName, String solution, SolutionQuality solutionQuality) {
		this.algorithmName = algorithmName;
		this.solution = solution;
		this.solutionQuality = solutionQuality;
	}

	/**
	 * @return quality
	 */
	public double quality() {
		return solutionQuality.quality();
	}

	/**
	 * @return algorithm name
	 */
	public String getAlgorithmName() {
		return algorithmName;
	}

	/**
	 * @return solution
	 */
	public String getSolution() {
		return solution;
	}

	public SolutionQuality getSolutionQuality() {
		return solutionQuality;
	}

}
